# Jekyll Defaults
title: Thatcher
description: Gymnastics in urban mathematics.
author: Thatcher Clay
#baseurl: "https://sirpthatch.github.io"

url: "https://sirpthatch.github.io"
#url: "http://127.0.0.1:4000"
github: https://github.com/sirpthatch
twitter_username: thatcherclay
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
