# Jekyll Defaults
title: Thatcher
description: Muses of a quantified self.
baseurl: "https://sirpthatch.github.io" # the subpath of your site, e.g. /blog

url: "https://sirpthatch.github.io"
#url: "http://127.0.0.1:4000"
github: https://github.com/sirpthatch
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
