# Jekyll Defaults
title: Thatcher
description: Muses of a quantified self.
author: Thatcher Clay
baseurl: "/"

url: "https://sirpthatch.github.io"
#url: "http://127.0.0.1:4000"
github: https://github.com/sirpthatch
twitter_username: sirpthatch
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
